# This is a basic workflow to help you get started with Actions

name: Update rekidai.min.json

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - 'static/rekidai.json'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - run: |
          git config --local user.email "workflow@example.com"
          git config --local user.name "workflow"
          git pull
          jq . static/rekidai.json > static/rekidai.json.tmp && mv -f static/rekidai.json.tmp static/rekidai.json
          jq -c < static/rekidai.json > rekidai.min.json
          sed -i 's/https:\/\/www\.youtube\.com/https:\/\/youtu\.be/g' rekidai.json
          git add rekidai.min.json static/rekidai.json
          git commit -m "Automatically updated by Workflow Action"
          git push origin main

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
